# Generated by Django 4.1.5 on 2023-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='images')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
